name: Windows-Msys2

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/msys2.yml'
      - premake/**
jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make
          python3
          mingw-w64-x86_64-clang 
          mingw-w64-x86_64-llvm

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: premake gmake2
      run: |
          cd premake
          ./premake5.exe gmake2 --without-tinfo #--llvm-root=

    - name: make config=release
      shell: msys2 {0}
      run: |
          cd project/gmake2
          make config=release verbose=1
          cd ../../bin/gmake2/Release
          ./ccccc_test
          LD_LIBRARY_PATH=/usr/local/lib ./ccccc --help

    - name: Upload ccccc
      uses: actions/upload-artifact@v4
      with:
        name: ccccc
        path: |
            bin/gmake2/Release/*.*

    - name: Upload dll
      uses: actions/upload-artifact@v4
      with:
        name: ccccc_dll
        path: |
            D:/a/_temp/msys64/mingw64/bin/libffi-*.dll        # libffi-8.dll
            D:/a/_temp/msys64/mingw64/bin/libgcc_s_seh-*.dll  # libgcc_s_seh-1.dll
            D:/a/_temp/msys64/mingw64/bin/libiconv-*.dll      # libiconv-2.dll
            D:/a/_temp/msys64/mingw64/bin/libLLVM-*.dll       # libLLVM-18.dll
            D:/a/_temp/msys64/mingw64/bin/liblzma-*.dll       # liblzma-5.dll
            D:/a/_temp/msys64/mingw64/bin/libstdc++-*.dll     # libstdc++-6.dll
            D:/a/_temp/msys64/mingw64/bin/libwinthread-*.dll  # libwinthread-1.dll
            D:/a/_temp/msys64/mingw64/bin/libxml2-*.dll       # libxml2-2.dll
            D:/a/_temp/msys64/mingw64/bin/libzstd.dll
            D:/a/_temp/msys64/mingw64/bin/zlib1.dll
