name: Windows-Msys2

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/msys2.yml'
      - premake5.lua
jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make
          python3
          mingw-w64-x86_64-clang 
          mingw-w64-x86_64-llvm

    - uses: Jarod42/install-premake5@v1

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: premake gmake2
      run: |
          premake5.exe gmake2 --without-tinfo #--llvm-root=

    - name: make config=release
      shell: msys2 {0}
      run: |
          cd project/gmake2
          make config=release verbose=1
          cd ../../bin/gmake2/Release
          ./ccccc_test
          ./ccccc --version
          ./ccccc --help

    - name: prepare for upload # upload-artifact requires a common root path
      shell: msys2 {0}
      run: |
        mkdir ccccc
        cp bin/gmake2/Release/ccccc.exe ccccc/
        cp /D/a/_temp/msys64/mingw64/bin/libffi-*.dll       ccccc/
        cp /D/a/_temp/msys64/mingw64/bin/libgcc_s_seh-*.dll ccccc/
        cp /D/a/_temp/msys64/mingw64/bin/libiconv-*.dll     ccccc/
        cp /D/a/_temp/msys64/mingw64/bin/libLLVM-*.dll      ccccc/
        cp /D/a/_temp/msys64/mingw64/bin/liblzma-*.dll      ccccc/
        cp /D/a/_temp/msys64/mingw64/bin/libstdc++-*.dll    ccccc/
        cp /D/a/_temp/msys64/mingw64/bin/libwin*thread-*.dll ccccc/
        cp /D/a/_temp/msys64/mingw64/bin/libxml2-*.dll      ccccc/
        cp /D/a/_temp/msys64/mingw64/bin/libzstd.dll        ccccc/ 
        cp /D/a/_temp/msys64/mingw64/bin/zlib1.dll          ccccc/ 

    - name: Upload ccccc
      uses: actions/upload-artifact@v4
      with:
        name: ccccc
        path: |
            ccccc/*.*
