name: Windows-Msys2

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/msys2.yml'
      - premake5.lua
jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make
          python3
          mingw-w64-x86_64-clang 
          mingw-w64-x86_64-llvm

    - uses: Jarod42/install-premake5@v3

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: premake gmake2
      run: |
          premake5.exe gmake2 --without-tinfo #--llvm-root=

    - name: make config=release
      shell: msys2 {0}
      run: |
          cd project/gmake2
          make config=release verbose=1
          cd ../../bin/gmake2/Release
          ./ccccc_test
          ./ccccc --version
          ./ccccc --help

    - name: prepare for upload # upload-artifact requires a common root path
      shell: msys2 {0}
      run: |
        mkdir ccccc
        cp bin/gmake2/Release/ccccc.exe ccccc/
        python mingw_deploy.py ccccc/ccccc.exe

    - name: Upload ccccc
      uses: actions/upload-artifact@v4
      with:
        name: ccccc
        path: |
            ccccc/*.exe

    - name: Upload ccccc dependencies
      uses: actions/upload-artifact@v4
      with:
        name: ccccc_dll
        path: |
            ccccc/*.dll
