name: Windows-Msys2

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/msys2.yml'
      - premake5.lua
jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make
          python3
          mingw-w64-x86_64-clang 
          mingw-w64-x86_64-llvm

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: checkout premake5
      uses: actions/checkout@v4
      with:
          repository: premake/premake-core
          path: premake-build

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build premake5
      run: |
        $vcvarall_path = vswhere -find VC\Auxiliary\Build\vcvarsall.bat
        cmd.exe /c "call ""$vcvarall_path"" x86_amd64 && cd premake-build && nmake -f Bootstrap.mak MSDEV=vs2022 windows-msbuild PLATFORM=Win32 CONFIG=release && cp bin/release/premake5.exe ../"

    - name: premake gmake2
      run: |
          ./premake5.exe gmake2 --without-tinfo #--llvm-root=

    - name: make config=release
      shell: msys2 {0}
      run: |
          cd project/gmake2
          make config=release verbose=1
          cd ../../bin/gmake2/Release
          ./ccccc_test
          ./ccccc --version
          ./ccccc --help

    - name: Upload ccccc
      uses: actions/upload-artifact@v4
      with:
        name: ccccc
        path: |
            bin/gmake2/Release/*.*

    - name: Upload dll
      uses: actions/upload-artifact@v4
      with:
        name: ccccc_dll
        path: |
            D:/a/_temp/msys64/mingw64/bin/libffi-*.dll        # libffi-8.dll
            D:/a/_temp/msys64/mingw64/bin/libgcc_s_seh-*.dll  # libgcc_s_seh-1.dll
            D:/a/_temp/msys64/mingw64/bin/libiconv-*.dll      # libiconv-2.dll
            D:/a/_temp/msys64/mingw64/bin/libLLVM-*.dll       # libLLVM-18.dll
            D:/a/_temp/msys64/mingw64/bin/liblzma-*.dll       # liblzma-5.dll
            D:/a/_temp/msys64/mingw64/bin/libstdc++-*.dll     # libstdc++-6.dll
            D:/a/_temp/msys64/mingw64/bin/libwinthread-*.dll  # libwinthread-1.dll
            D:/a/_temp/msys64/mingw64/bin/libxml2-*.dll       # libxml2-2.dll
            D:/a/_temp/msys64/mingw64/bin/libzstd.dll
            D:/a/_temp/msys64/mingw64/bin/zlib1.dll
